apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  namespace: istio-system
spec:
  istio:
    kiali:
      enabled: false
    tracing:
      enabled: false
    global:
      defaultPodDisruptionBudget:
        enabled: false
      disablePolicyChecks: false
      multitenant: true
      omitSidecarInjectorConfigMap: true
      proxy:
        autoInject: disabled
    grafana:
      enabled: false
    sidecarInjectorWebhook:
      enabled: false
    mixer:
      enabled: false
      policy:
        enabled: false
      telemetry:
        enabled: false
    prometheus:
      enabled: false
    gateways:
      cluster-local-gateway:
        autoscaleEnabled: false
        enabled: true
        labels:
          app: cluster-local-gateway
          istio: cluster-local-gateway
        ports:
          - name: status-port
            port: 15020
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
      istio-egressgateway:
        enabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        type: LoadBalancer
    istio_cni:
      enabled: true
    pilot:
      autoscaleEnabled: false
      sidecar: false
